name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

  ## 📦 Installation

  ```bash
  npm install
  ```

  ## 🚀 Quick Start

  ```bash
  npm run dev
  ```

  ## 📚 Documentation

  See [README.md](README.md) for full documentation.

  ## 🔗 Links

  - [Live Demo](#)
  - [Documentation](README.md)
  - [Issues](https://github.com/FrankFMY/portfolio-landing-nextjs/issues)
  - [Pull Requests](https://github.com/FrankFMY/portfolio-landing-nextjs/pulls)

  ---

  **Full Changelog**: https://github.com/FrankFMY/portfolio-landing-nextjs/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
