# Количество дней активности перед пометки как stale
daysUntilStale: 60
# Количество дней после пометки как stale перед закрытия
daysUntilClose: 7
# Issues с этими лейблами не будут помечены как stale
exemptLabels:
  - pinned
  - security
  - bug
  - enhancement
  - documentation
  - good first issue
  - help wanted
# PR с этими лейблами не будут помечены как stale
exemptPullRequestLabels:
  - pinned
  - security
  - work in progress
  - draft
# Issues с этими лейблами будут автоматически закрыты
exemptAllLabels:
  - pinned
# Комментарий для stale issues
staleIssueMessage: |
  This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.
# Комментарий для stale PR
stalePrMessage: |
  This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.
# Комментарий при закрытии
closeIssueMessage: |
  This issue has been automatically closed due to inactivity. If you believe this issue should remain open, please comment and it will be reopened.
# Комментарий при закрытии PR
closePrMessage: |
  This pull request has been automatically closed due to inactivity. If you believe this PR should remain open, please comment and it will be reopened.
# Лейбл для stale issues
staleIssueLabel: no-issue-activity
# Лейбл для stale PR
stalePrLabel: no-pr-activity
# Включить обработку issues
enableIssue: true
# Включить обработку PR
enablePullRequest: true
# Включить обработку комментариев
enableComment: true
# Количество дней без комментариев перед пометки как stale
daysUntilStaleForComment: 30
# Комментарий для stale комментариев
staleCommentMessage: |
  This comment has been automatically marked as stale because it has not had recent activity. It will be hidden if no further activity occurs.
