name: Bundle Size Check

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]

env:
  NODE_VERSION: '18'

jobs:
  bundle-size:
    name: Bundle Size Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Analyze bundle size
        run: npm run analyze
        env:
          ANALYZE: true

      - name: Upload bundle analysis
        uses: actions/upload-artifact@v4
        with:
          name: bundle-analysis
          path: .next/analyze/
          retention-days: 30

      - name: Comment bundle size on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            try {
              const analyzePath = '.next/analyze';
              const files = fs.readdirSync(analyzePath);
              
              let bundleInfo = '## 📦 Bundle Size Analysis\n\n';
              bundleInfo += '| File | Size | Gzipped |\n';
              bundleInfo += '|------|------|--------|\n';
              
              files.forEach(file => {
                if (file.endsWith('.html')) {
                  const content = fs.readFileSync(path.join(analyzePath, file), 'utf8');
                  const sizeMatch = content.match(/Total Size: ([\d.]+) kB/);
                  const gzippedMatch = content.match(/Gzipped Size: ([\d.]+) kB/);
                  
                  if (sizeMatch && gzippedMatch) {
                    bundleInfo += `| ${file.replace('.html', '')} | ${sizeMatch[1]} kB | ${gzippedMatch[1]} kB |\n`;
                  }
                }
              });
              
              bundleInfo += '\n💡 **Tip:** Keep bundle size under 500 kB for optimal performance.';
              
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: bundleInfo,
              });
            } catch (error) {
              console.log('Bundle analysis files not found or error occurred:', error.message);
            }
