name: Create Labels

on:
  push:
    branches: [main]
    paths:
      - '.github/labels.yml'

jobs:
  create-labels:
    name: Create Labels
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Labels
        uses: actions/github-script@v7
        with:
          script: |
            const yaml = require('js-yaml');
            const fs = require('fs');

            try {
              const labelsConfig = yaml.load(fs.readFileSync('.github/labels.yml', 'utf8'));
              
              for (const label of labelsConfig.labels) {
                try {
                  await github.rest.issues.createLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: label.name,
                    color: label.color,
                    description: label.description,
                  });
                  console.log(`✅ Created label: ${label.name}`);
                } catch (error) {
                  if (error.status === 422) {
                    // Label already exists, update it
                    await github.rest.issues.updateLabel({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      name: label.name,
                      color: label.color,
                      description: label.description,
                    });
                    console.log(`🔄 Updated label: ${label.name}`);
                  } else {
                    console.error(`❌ Error with label ${label.name}:`, error.message);
                  }
                }
              }
              
              console.log('🎉 All labels processed successfully!');
            } catch (error) {
              console.error('❌ Error reading labels config:', error.message);
              core.setFailed(error.message);
            }
