name: Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  labeler:
    name: Auto Labeler
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Auto Label PR
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add size label
        uses: actions/github-script@v7
        with:
          script: |
            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            const totalChanges = files.reduce((acc, file) => acc + file.changes, 0);

            let sizeLabel = '';
            if (totalChanges <= 10) {
              sizeLabel = 'size: XS';
            } else if (totalChanges <= 30) {
              sizeLabel = 'size: S';
            } else if (totalChanges <= 100) {
              sizeLabel = 'size: M';
            } else if (totalChanges <= 500) {
              sizeLabel = 'size: L';
            } else {
              sizeLabel = 'size: XL';
            }

            try {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: [sizeLabel],
              });
              console.log(`✅ Added size label: ${sizeLabel} (${totalChanges} changes)`);
            } catch (error) {
              console.log(`⚠️ Could not add size label: ${error.message}`);
            }
