name: Release

on:
  push:
    tags:
      - 'v*'

env:
  NODE_VERSION: '18'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build

      - name: Generate release notes
        id: release_notes
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          publish: true
          prerelease: false
          config-name: release-drafter.yml

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: .next/
          retention-days: 30

      - name: Comment on release
        uses: actions/github-script@v7
        with:
          script: |
            const { data: release } = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: context.ref.replace('refs/tags/', ''),
            });

            const comment = `## 🚀 Release ${{ github.ref_name }} Published!

            ### 📦 Build Status: ✅ Success

            - **Tests:** ✅ All tests passed
            - **Build:** ✅ Production build successful
            - **Linting:** ✅ Code quality checks passed

            ### 🔗 Links

            - **Release:** ${release.html_url}
            - **Download:** ${release.tarball_url}
            - **Documentation:** https://github.com/FrankFMY/portfolio-landing-nextjs#readme

            ### 📋 Next Steps

            1. Deploy to production
            2. Update documentation if needed
            3. Notify stakeholders

            ---

            *This release was automatically generated by GitHub Actions*`;

            await github.rest.issues.createComment({
              issue_number: release.id,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment,
            });
